# Generated by Django 5.0.3 on 2024-04-18 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='github',
        ),
    ]
