# Generated by Django 5.0.3 on 2024-04-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_customuser_github'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Facebook with url'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Instagram with url'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='site',
            field=models.URLField(blank=True, null=True, verbose_name='Web site'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram with url'),
        ),
    ]
